knp_snappy:
    pdf:
        enabled: true
        binary: '%kernel.project_dir%/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'
        options:
            page-size: A4
            encoding: UTF-8