services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Command\CheckDatabaseConnectionCommand:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
        tags:
            - { name: 'console.command' }

    App\Service\CloudService:
        arguments:
            $cloudconvertApiKey: '%env(CLOUDCONVERT_API_KEY)%'

parameters:
    upload_directory: '%kernel.project_dir%/public/uploads'