services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Command\CheckDatabaseConnectionCommand:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
        tags:
            - { name: 'console.command' }

    App\Service\CloudService:
        arguments:
            $sofficePath: '%app.soffice_path%'

parameters:
    upload_directory: '%kernel.project_dir%/public/uploads'
    app.soffice_path: 'C:\\Program Files\\LibreOffice\\program\\soffice.exe'